# Custom minimal format - character first, then directory and git branch
format = "$character$directory$git_branch "
add_newline = false

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](blue)'
error_symbol = '[](red)'

[package]
disabled = true
format = '\[[$symbol$version]($style)\]'

[directory]
disabled = false
truncation_length = 0

# Git 
[git_branch]
symbol = ""
format = '\([$symbol $branch]($style)\)'

[git_status]
disabled = true
format = '([\[$all_status$ahead_behind\]]($style))'


