# Custom minimal format - character first, then directory and git branch
format = "$character$directory$git_branch$python "
add_newline = false

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](blue)'
error_symbol = '[](red)'
# vimcmd_symbol = '[V](blue)'

[package]
disabled = true
format = '\[[$symbol$version]($style)\]'

[directory]
disabled = false
truncation_length = 0

# Git 
[git_branch]
symbol = ""
format = '\([$symbol $branch]($style)\)'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style))'

[python]
# show just the env name, not the version/symbol
format = '\[[$symbol$virtualenv]($style)\]'
style = "yellow"
symbol = " "
detect_extensions = []
detect_files = []
detect_folders = []
